<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Gallery Test</title>
    
    <link rel="stylesheet" type="text/css" media="screen" href="/lib/css/base.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/lib/css/jq-gallery.css" />
    
    <script type="text/javascript" src="/lib/js/jquery.js"></script>
    <script type="text/javascript" src="/lib/js/swfobject.js"></script>
    <script type="text/javascript" src="/lib/js/demo-data.js"></script>
    <script type="text/javascript" src="/lib/js/jq-gallery.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('a[rel=gallery]').gallery();
            $('a[rel=video]').video();
        });
    </script>
</head>
<body>
    <p><a href="" rel="gallery">trigger</a> <a href="ZC8OIWWczLc" rel="video">video</a></p>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tellus orci. Suspendisse at cursus diam. Vivamus eu venenatis urna. Nam cursus lacinia enim non mattis. Aliquam fermentum nisi at turpis consequat sit amet semper ante consectetur. Donec nulla sem, ultricies quis malesuada quis, feugiat a dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vulputate, massa ut eleifend consectetur, risus nunc eleifend orci, vel convallis mauris velit eget purus. Proin interdum tellus sed enim viverra ut commodo lectus tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac lacus nunc, sed consequat eros. Nunc interdum molestie felis quis hendrerit. Maecenas lacus leo, tempus sed eleifend ut, tempus id enim. Cras bibendum ante vel arcu tempus iaculis. Nulla facilisi. Suspendisse nisl neque, adipiscing et faucibus nec, aliquam ac erat. Morbi erat velit, posuere eu bibendum nec, gravida quis nunc. Nullam condimentum, mauris at commodo pharetra, nisl ipsum rutrum massa, vel vehicula sem sapien ut lorem.</p>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tellus orci. Suspendisse at cursus diam. Vivamus eu venenatis urna. Nam cursus lacinia enim non mattis. Aliquam fermentum nisi at turpis consequat sit amet semper ante consectetur. Donec nulla sem, ultricies quis malesuada quis, feugiat a dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vulputate, massa ut eleifend consectetur, risus nunc eleifend orci, vel convallis mauris velit eget purus. Proin interdum tellus sed enim viverra ut commodo lectus tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac lacus nunc, sed consequat eros. Nunc interdum molestie felis quis hendrerit. Maecenas lacus leo, tempus sed eleifend ut, tempus id enim. Cras bibendum ante vel arcu tempus iaculis. Nulla facilisi. Suspendisse nisl neque, adipiscing et faucibus nec, aliquam ac erat. Morbi erat velit, posuere eu bibendum nec, gravida quis nunc. Nullam condimentum, mauris at commodo pharetra, nisl ipsum rutrum massa, vel vehicula sem sapien ut lorem.</p>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tellus orci. Suspendisse at cursus diam. Vivamus eu venenatis urna. Nam cursus lacinia enim non mattis. Aliquam fermentum nisi at turpis consequat sit amet semper ante consectetur. Donec nulla sem, ultricies quis malesuada quis, feugiat a dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vulputate, massa ut eleifend consectetur, risus nunc eleifend orci, vel convallis mauris velit eget purus. Proin interdum tellus sed enim viverra ut commodo lectus tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac lacus nunc, sed consequat eros. Nunc interdum molestie felis quis hendrerit. Maecenas lacus leo, tempus sed eleifend ut, tempus id enim. Cras bibendum ante vel arcu tempus iaculis. Nulla facilisi. Suspendisse nisl neque, adipiscing et faucibus nec, aliquam ac erat. Morbi erat velit, posuere eu bibendum nec, gravida quis nunc. Nullam condimentum, mauris at commodo pharetra, nisl ipsum rutrum massa, vel vehicula sem sapien ut lorem.</p>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tellus orci. Suspendisse at cursus diam. Vivamus eu venenatis urna. Nam cursus lacinia enim non mattis. Aliquam fermentum nisi at turpis consequat sit amet semper ante consectetur. Donec nulla sem, ultricies quis malesuada quis, feugiat a dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vulputate, massa ut eleifend consectetur, risus nunc eleifend orci, vel convallis mauris velit eget purus. Proin interdum tellus sed enim viverra ut commodo lectus tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac lacus nunc, sed consequat eros. Nunc interdum molestie felis quis hendrerit. Maecenas lacus leo, tempus sed eleifend ut, tempus id enim. Cras bibendum ante vel arcu tempus iaculis. Nulla facilisi. Suspendisse nisl neque, adipiscing et faucibus nec, aliquam ac erat. Morbi erat velit, posuere eu bibendum nec, gravida quis nunc. Nullam condimentum, mauris at commodo pharetra, nisl ipsum rutrum massa, vel vehicula sem sapien ut lorem.</p>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tellus orci. Suspendisse at cursus diam. Vivamus eu venenatis urna. Nam cursus lacinia enim non mattis. Aliquam fermentum nisi at turpis consequat sit amet semper ante consectetur. Donec nulla sem, ultricies quis malesuada quis, feugiat a dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vulputate, massa ut eleifend consectetur, risus nunc eleifend orci, vel convallis mauris velit eget purus. Proin interdum tellus sed enim viverra ut commodo lectus tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac lacus nunc, sed consequat eros. Nunc interdum molestie felis quis hendrerit. Maecenas lacus leo, tempus sed eleifend ut, tempus id enim. Cras bibendum ante vel arcu tempus iaculis. Nulla facilisi. Suspendisse nisl neque, adipiscing et faucibus nec, aliquam ac erat. Morbi erat velit, posuere eu bibendum nec, gravida quis nunc. Nullam condimentum, mauris at commodo pharetra, nisl ipsum rutrum massa, vel vehicula sem sapien ut lorem.</p>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tellus orci. Suspendisse at cursus diam. Vivamus eu venenatis urna. Nam cursus lacinia enim non mattis. Aliquam fermentum nisi at turpis consequat sit amet semper ante consectetur. Donec nulla sem, ultricies quis malesuada quis, feugiat a dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vulputate, massa ut eleifend consectetur, risus nunc eleifend orci, vel convallis mauris velit eget purus. Proin interdum tellus sed enim viverra ut commodo lectus tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac lacus nunc, sed consequat eros. Nunc interdum molestie felis quis hendrerit. Maecenas lacus leo, tempus sed eleifend ut, tempus id enim. Cras bibendum ante vel arcu tempus iaculis. Nulla facilisi. Suspendisse nisl neque, adipiscing et faucibus nec, aliquam ac erat. Morbi erat velit, posuere eu bibendum nec, gravida quis nunc. Nullam condimentum, mauris at commodo pharetra, nisl ipsum rutrum massa, vel vehicula sem sapien ut lorem.</p>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tellus orci. Suspendisse at cursus diam. Vivamus eu venenatis urna. Nam cursus lacinia enim non mattis. Aliquam fermentum nisi at turpis consequat sit amet semper ante consectetur. Donec nulla sem, ultricies quis malesuada quis, feugiat a dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vulputate, massa ut eleifend consectetur, risus nunc eleifend orci, vel convallis mauris velit eget purus. Proin interdum tellus sed enim viverra ut commodo lectus tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac lacus nunc, sed consequat eros. Nunc interdum molestie felis quis hendrerit. Maecenas lacus leo, tempus sed eleifend ut, tempus id enim. Cras bibendum ante vel arcu tempus iaculis. Nulla facilisi. Suspendisse nisl neque, adipiscing et faucibus nec, aliquam ac erat. Morbi erat velit, posuere eu bibendum nec, gravida quis nunc. Nullam condimentum, mauris at commodo pharetra, nisl ipsum rutrum massa, vel vehicula sem sapien ut lorem.</p>

</body>
</html>